apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-sample-app-deployment
  namespace: dev
  labels:
    app: docker-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-sample-app
  template:
    metadata:
      labels:
        app: docker-sample-app
    spec:
      containers:
      - name: docker-sample-app
        image: tbrowet/docker-sample-app:dev-d657c64
        ports:
        - containerPort: 80