---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: docker-sample-app-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: docker-sample-app-dev
  chart:
    git: git@github.com:tbrowet/helm-operator-get-started
    path: charts/docker-sample-app
    ref: master
  values:
    image:
      repository: tbrowet/docker-sample-app
      tag: dev-d657c64
    replicaCount: 1