apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-sample-app-deployment
  labels:
    app: docker-sample-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: docker-sample-app
  template:
    metadata:
      labels:
        app: docker-sample-app
    spec:
      containers:
      - name: docker-sample-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80